# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trivy < Formula
  desc "Scanner for vulnerabilities in container images, file systems, and Git repositories, as well as for configuration issues"
  homepage "https://github.com/aquasecurity/trivy"
  version "0.37.19"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DmitriyLewen/trivy/releases/download/v0.37.19/trivy_0.37.19_macOS-64bit.tar.gz"
      sha256 "906d099dbaae607c10de84613160b425f216dda7a8bc0f5261044cdea43bcd02"

      def install
        bin.install "trivy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DmitriyLewen/trivy/releases/download/v0.37.19/trivy_0.37.19_macOS-ARM64.tar.gz"
      sha256 "874c3c278ebaa71175c536fa5f3ac554bc4d4fe066d772d42bb23d17f8ae43e3"

      def install
        bin.install "trivy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DmitriyLewen/trivy/releases/download/v0.37.19/trivy_0.37.19_Linux-ARM64.tar.gz"
      sha256 "f91d7f333f73125b0c649832811735a3657cf4917a423068186f50b09a780ba4"

      def install
        bin.install "trivy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DmitriyLewen/trivy/releases/download/v0.37.19/trivy_0.37.19_Linux-64bit.tar.gz"
      sha256 "04d8d2d17850d5ae734d246f0e5c7007b4e5c5d7b548a74c61e0f2e1f38dfc05"

      def install
        bin.install "trivy"
      end
    end
  end

  test do
    system "#{bin}/trivy", "--version"
  end
end
