# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trivy < Formula
  desc "Scanner for vulnerabilities in container images, file systems, and Git repositories, as well as for configuration issues"
  homepage "https://github.com/aquasecurity/trivy"
  version "0.37.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DmitriyLewen/trivy/releases/download/v0.37.13/trivy_0.37.13_macOS-64bit.tar.gz"
      sha256 "3ee398a6c08e556b9de7d4257c19558d776aadf25d247022d2c0bc0f1a17d14d"

      def install
        bin.install "trivy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DmitriyLewen/trivy/releases/download/v0.37.13/trivy_0.37.13_macOS-ARM64.tar.gz"
      sha256 "102219dd16d027860c851f22b151776a674efcac3d750349dbe582e04f29ca25"

      def install
        bin.install "trivy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/DmitriyLewen/trivy/releases/download/v0.37.13/trivy_0.37.13_Linux-64bit.tar.gz"
      sha256 "a42f636e625e89ea98c3834560e49abdb63b017ddfe38247ae71bec9fb60c33b"

      def install
        bin.install "trivy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DmitriyLewen/trivy/releases/download/v0.37.13/trivy_0.37.13_Linux-ARM64.tar.gz"
      sha256 "57419d1225ffaca8fe270793f94a194ab1bd21450906e5be926dd7d0d30f38a1"

      def install
        bin.install "trivy"
      end
    end
  end

  test do
    system "#{bin}/trivy", "--version"
  end
end
